[package]
name = "ic-canister-kit"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
include = ["src", "Cargo.toml", "LICENSE", "README.md"]
description = "An ic canister package"
authors = ["Anubis Awooo"]

# [lib]
# path = "src/lib.rs"
# crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[features]
default = ["all"]

# 和身份相关的
identity = ["candid", "ic-cdk", "sha2", "crc32fast", "hex"] # 身份相关

# 和罐子相关的
canister_cycles = ["candid", "serde"] # 罐子余额
canister_status = ["identity"] # 罐子状态
canister_create = ["identity"] # 罐子创建
canister_settings = ["identity"] # 罐子设置
canister_codes = ["identity"] # 罐子代码
canister_deploy = [
    "canister_status",
    "canister_create",
    "canister_codes",
] # 罐子部署
canister_call = ["identity"] # 罐子调用
canister_managed = [
    "canister_cycles",
    "canister_status",
    "canister_codes",
    "canister_deploy",
] # 管理罐子

# 和数字相关的
number_random = ["ic-cdk"]                       # 随机数
number_mix = ["number_random", "sha2", "base32"] # 混合数字

# 代币相关
token_ledger = ["identity", "serde"] # LEDGER 标准

# 通用工具
common_times = ["ic-cdk"] # 时间相关
# logs = ["times"]                         # 日志记录
# pages = []                               # 分页查询
# results = []                             # 结果类型
# tasks = ["ic-cdk-timers"]                # 定时任务
# stable = ["ic-cdk"]                      # 持久化
# initial = ["stable"]                     # 初始化
# permissions = ["stable", "candid"]       # 权限
# maintainable = ["stable"]                # 维护
# uploads = ["stable"]                     # 分片上传
# nft = ["identity", "stable"]             # NFT
# nft_ext = ["nft"]                        # NFT EXT 标准
# nft_ticket = ["nft"]                     # NFT 是否具有门票功能
# nft_limit = ["nft"]                      # NFT 是否限制指定时间的功能
# nft_traits = ["nft"]                     # NFT 的属性记录
# http = ["candid", "serde", "serde_json"] # http 相关

all = [
    "identity",
    "canister_cycles",
    "canister_status",
    "canister_create",
    "canister_settings",
    "canister_codes",
    "canister_deploy",
    "canister_call",
    "canister_managed",
    "number_random",
    "number_mix",
    "token_ledger",
    "common_times",
    # "logs",
    # "pages",
    # "results",
    # "tasks",
    # "stable",
    # "initial",
    # "permissions",
    # "maintainable",
    # "uploads",
    # "nft",
    # "nft_ext",
    # "nft_ticket",
    # "nft_limit",
    # "nft_traits",
    # "http",
]

[dependencies]
candid = { version = "0.9.3", optional = true }        # ic-cdk required
ic-cdk = { version = "0.10.0", optional = true }
ic-cdk-timers = { version = "0.4.0", optional = true } # 定时器

sha2 = { version = "0.10.6", optional = true }     # hash
crc32fast = { version = "1.3.2", optional = true } # 循环校验
hex = { version = "0.4.3", optional = true }       # 16进制

base32 = { version = "0.4.0", optional = true } # base32 加密解密

serde = { version = "1", optional = true, features = ["derive"] } # 序列化/反序列化框架
serde_json = { version = "1.0.95", optional = true }              # json

# ic-kit = "0.4.8"
# cap-sdk = "0.2.4"
# cap-sdk-core = "0.2.3"
